@startuml

class Garage{
  maxPosti : int
  postiOcc : int
  autoInGarage : Auto[maxPosti]
  imissioneAuto(Auto) : bool
  estraiAuto(int) : Auto
  stampaSituazione() : void
}


class Auto{
  marca : string
  anno : int
  cilindrata : int
  porte : int
  alimentazione : string
  toString()
  getMarca() : string
}

Garage "0..1"--"0..15" Auto : Può ospitare

@enduml
